apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: community-windows-machine-config-operator
  namespace: openshift-windows-machine-config-operator
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: community-windows-machine-config-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
