apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-windows-machine-config-operator

bases:
  - ../../base

patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: community-windows-machine-config-operator
      namespace: openshift-windows-machine-config-operator
    path: patch-channel.yaml
